DEFAULT_TRACE_LINES_WIDTH = 4
MIN_TRACE_DX = 1e-9

DEFAULT_MOUSE_LINE_WIDTH = 4
DEFAULT_MOUSE_LINE_LENGTH = 4

# length = 1    ~  1 / 100  of the length of the diagonal
# length = 10   ~  1 / 10   of the length of the diagonal
DEFAULT_ARROW_LENGTH = 4
DEFAULT_ARROW_WIDTH = 3
DEFAULT_NUM_ARROWS = 21
MAX_NUM_ARROWS = 100

DEFAULT_FUNCTION = "-x*y"

AXIS_RATIO = 1.5
DEFAULT_XMIN = -2.5
DEFAULT_XMAX = 2.5
DEFAULT_YMIN = DEFAULT_XMIN / AXIS_RATIO
DEFAULT_YMAX = DEFAULT_XMAX / AXIS_RATIO
